version: '3.9'

services:
  api:
    build: ./sonitus-api
    container_name: sonitus-api
    ports:
      - "3000:3000"
    env_file:
      - ./sonitus-api/.env
    restart: unless-stopped

  websocket:
    build: ./sonitus-websocket
    container_name: sonitus-websocket
    ports:
      - "3001:3001"
    env_file:
      - ./sonitus-websocket/.env
    restart: unless-stopped